Algoritmo "media_idades"

Var

idade,soma,cont,media : real

Inicio
      escreval("Digite uma idade:")
      leia(idade)
      soma <- 0
      cont <- 0
      enquanto x >= 0 faca
      soma <- soma + idade
      cont <- cont + 1
      leia (idade)
      
      fimenquanto
      media <- soma /cont
      
      se cont = 0 entao
      escreval("impossivel calcular ")
      senao
       media <- soma /cont
       escreval("Media igual =", media)
      



Fimalgoritmo