Algoritmo "terreno"

Var

 largura, comprimento ,metroQuadrado, area, preco: real

Inicio
   escreva("digite a largura do terreno: ")
   leia (largura)
   escreva("digite o comrpimento do terreno: ")
   leia (comprimento)
   escreva("digite o valor do metro quadrado: ")
   leia (metroQuadrado)
   
   area <- largura * comprimento
   preco <- area*metroQuadrado
   
   escreval("a área do terreno é: ", area: 8:2, " e o preço é : ", preco: 8:2)


Fimalgoritmo